[package]
name = "near-da-rpc"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
log = "*"
eyre = "0.6"
async-trait = "*"
tokio = { version = "1.0", features = ["full"] }
futures = "*"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "*", features = ["hex"] }
borsh = { workspace = true }

near-crypto = { git = "https://github.com/near/nearcore", rev = "46dc4374157a40b3bdd1ef88139b95b69d500bd4" }
near-jsonrpc-client = { git = "https://github.com/encody/near-jsonrpc-client-rs", branch = "patch/unpin-tokio" }
near-jsonrpc-primitives = { git = "https://github.com/near/nearcore", rev = "46dc4374157a40b3bdd1ef88139b95b69d500bd4" }
near-primitives = { git = "https://github.com/near/nearcore", rev = "46dc4374157a40b3bdd1ef88139b95b69d500bd4" }
near-da-primitives = { path = "../primitives" }

[dev-dependencies]
pretty_env_logger = "*"

[build-dependencies]
cbindgen = "*"
which = "*"
